import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowRight, Download, Share2, Check, RefreshCw } from "lucide-react";
import { ButtonLink, WaveMark } from "./ui";
import { safeWebLink, saveFile, waveRequest } from "./workspace-client";
import type { PublicWave as PublicWaveRecord, ReceiptResult, WaveOffer, WavePass } from "./workspace-types";
import "./workspace.css";

const formatDate = (v: string) => new Date(v).toLocaleDateString(undefined, { dateStyle: "medium" });
function Evidence({ href }: { href: string }) { const safe = safeWebLink(href); return safe ? <a className="text-button" href={safe} target="_blank" rel="noreferrer">View Evidence <ArrowRight size={16} /></a> : null; }

export function PublicWave() {
  const { slug = "" } = useParams();
  const [latestReceipt, setLatestReceipt] = useState("");
  const [wave, setWave] = useState<PublicWaveRecord | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(""), [shared, setShared] = useState(false);
  useEffect(() => { let active = true; setLoading(true); setWave(null); setError(""); waveRequest<{wave:PublicWaveRecord}>("", undefined, slug).then(r => { if(active) setWave(r.wave); }).catch(e => { if(active) setError(e.message); }).finally(() => { if(active) setLoading(false); }); return () => { active = false; }; }, [slug]);
  const share = async () => { const url = `${window.location.origin}/waves/${slug}`; try { if (navigator.share) await navigator.share({title:wave?.title,url}); else { await navigator.clipboard.writeText(url); setShared(true); } } catch { setShared(false); } };
  if (loading) return <div className="workspace-page workspace-loading" role="status">Opening this Wave…</div>;
  if (error || !wave) return <div className="workspace-page"><section className="panel"><WaveMark /><h1>This Wave Is Not Available Yet.</h1><p>{error || "Published Waves appear here when the builder and team are ready to share them."}</p><div className="workspace-actions"><ButtonLink to="/waves">Explore Waves</ButtonLink><ButtonLink to="/now-lets-begin#wave-examples" secondary>Explore The Starting Models</ButtonLink></div></section></div>;
  return <div className="workspace-page" data-no-swipe>
    <header className="public-wave-hero"><WaveMark /><p className="eyebrow">{wave.template ? `${wave.template.toUpperCase()} WAVE` : "WAVES.FUND"}</p><h1>{wave.title}</h1><p>Trust People.<br/>And They Become Trustworthy.</p><button className="workspace-button secondary" onClick={share}>{shared ? <Check size={17}/> : <Share2 size={17}/>}{shared ? "Link Copied" : "Share This Wave"}</button></header>
    <div className="workspace-stack">
      <section className="panel"><p className="eyebrow">THE STORY</p><h2>What We’re Building Together</h2><p className="public-wave-story">{wave.story}</p><div className="workspace-entry"><p className="eyebrow">YOUR WAVE GUIDE</p><h3>{wave.guideName}</h3><p>{wave.guideBio}</p></div></section>
      <section className="panel public-wave-move"><p className="eyebrow">THE CURRENT MOVE</p><span className="workspace-badge">{wave.currentMove.status === "complete" ? "Complete" : "Help Welcome"}</span><h2 style={{marginTop:20}}>{wave.currentMove.title}</h2><dl className="workspace-detail"><div><dt>Responsible</dt><dd>{wave.currentMove.owner}</dd></div><div><dt>Help Needed</dt><dd>{wave.currentMove.needs}</dd></div><div><dt>Complete When</dt><dd>{wave.currentMove.completion}</dd></div>{wave.currentMove.outcome && <div><dt>What Changed</dt><dd>{wave.currentMove.outcome}</dd></div>}</dl>{wave.currentMove.evidence && <div className="workspace-actions"><Evidence href={wave.currentMove.evidence}/></div>}</section>
      {wave.currentMove.status === "open" && <OfferHelp wave={wave} onReceipt={setLatestReceipt}/>}
      <section className="panel"><p className="eyebrow">THE PEOPLE MOVING IT FORWARD</p><h2>Contributions & Carrying</h2>{!wave.contributions.length && !wave.carrying.length && <p>Agreed contributions and outcomes will appear here with permission. Each person’s help becomes part of the Journey.</p>}{wave.contributions.map((contribution,index)=><article className="workspace-entry" key={`contribution-${index}`}><span className="workspace-badge">Completed Contribution</span><h3>{contribution.name}</h3><p>{contribution.outcome}</p><Evidence href={contribution.evidence}/></article>)}{wave.carrying.map((person,index)=><article className="workspace-entry" key={`pass-${index}`}><span className="workspace-badge">{person.status === "accepted" ? "Carrying This Wave" : person.status}</span><h3>{person.name}</h3><p>{person.purpose}</p>{person.outcome && <p>{person.outcome}</p>}<Evidence href={person.evidence}/></article>)}</section>
      <section className="panel"><p className="eyebrow">YOU HELPED. HERE’S WHAT CHANGED.</p><h2>The Journey</h2>{wave.journey.length ? wave.journey.map(item=><article className="workspace-entry" key={item.id}><time dateTime={item.created}>{formatDate(item.created)}</time><h3>{item.title}</h3><p>{item.body}</p><Evidence href={item.evidence}/></article>) : <p>The next outcome will be shared here after the work is completed and approved.</p>}</section>
      <ReceiptTracker slug={slug} receivedReceipt={latestReceipt}/>
      <section className="panel"><h2>Build Your Own Wave.</h2><p>A Wave Guide works with you to design, build, and evolve the tools and story your mission needs. Begin with your vision, then agree your scope and fee together.</p><div className="workspace-actions"><ButtonLink to={`/apply${wave.template?`?waveType=${encodeURIComponent(wave.template)}`:""}`}>Bring Your Vision</ButtonLink><ButtonLink to="/guide/library" secondary>Explore The Guide Library</ButtonLink></div></section>
    </div>
  </div>;
}

function OfferHelp({wave,onReceipt}:{wave:PublicWaveRecord;onReceipt:(receipt:string)=>void}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[receipt,setReceipt]=useState("");
  const [requestId]=useState(()=>crypto.randomUUID());
  const submit=async (event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{const response=await waveRequest<{receipt:string}>("offer",{action:"offer",slug:wave.slug,moveId:wave.currentMove.id,name:String(form.get("name")||"").trim(),email:String(form.get("email")||"").trim(),message:String(form.get("message")||"").trim(),recognitionConsent:form.get("recognitionConsent")==="on",requestId,website:String(form.get("website")||"")});setReceipt(response.receipt);onReceipt(response.receipt);try{localStorage.setItem(`waves-offer-receipt:${wave.slug}`,response.receipt);}catch{/* A downloaded receipt remains available. */}}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <section className="panel" id="offer-help"><p className="eyebrow">YOUR CONTRIBUTION MATTERS</p><h2>{receipt?"Your Offer Is In Motion.":"Offer Your Help"}</h2>{receipt ? <><p>Your builder and Guide can now review your offer. Save this private receipt to see their response, track what happens, or withdraw your offer.</p><p className="workspace-receipt">{receipt}</p><button className="workspace-button" onClick={()=>saveFile(`${wave.slug}-contribution-receipt.json`,{receipt,slug:wave.slug,url:`https://www.waves.fund/waves/${wave.slug}`,kind:"offer"})}><Download size={17}/>Download My Receipt</button><p className="workspace-note">Keep your receipt private. Anyone with it can view and manage your offer.</p><a className="text-button" href="#my-contribution">Track My Contribution<ArrowRight size={16}/></a></> : <><p>Offer time, skills, a useful introduction, or another practical contribution to this move. The team will respond through your private receipt.</p><form className="workspace-form" onSubmit={submit}><div className="workspace-grid"><label>Your name<input name="name" autoComplete="name" required maxLength={120}/></label><label>Your email · private<input name="email" type="email" autoComplete="email" required maxLength={254}/></label></div><label>How would you like to help?<textarea name="message" required rows={5} maxLength={3000}/></label><label className="workspace-check"><input type="checkbox" name="recognitionConsent"/><span>You may show my name and completed contribution on the public Wave.</span></label><label className="workspace-check"><input type="checkbox" required/><span>I agree that the builder and assigned Guides may use these details to coordinate my offer. <Link to="/privacy">Privacy</Link></span></label><div style={{position:"absolute",left:-10000}} aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><button className="workspace-button" disabled={busy}>{busy?"Sending…":"Offer My Help"}<ArrowRight size={17}/></button></form></>}{error && <p className="workspace-message error" role="alert">{error}</p>}</section>;
}

function ReceiptTracker({slug,receivedReceipt}:{slug:string;receivedReceipt:string}) {
  const [receipt,setReceipt]=useState(()=>{try{return localStorage.getItem(`waves-offer-receipt:${slug}`)||"";}catch{return "";}}),[result,setResult]=useState<ReceiptResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[recognition,setRecognition]=useState(false);
  useEffect(() => { if (receivedReceipt) { setReceipt(receivedReceipt); setResult(null); } }, [receivedReceipt]);
  async function inspect(action="receipt",decision?:"accept"|"decline") {setBusy(true);setError("");try{const response=await waveRequest<ReceiptResult>(action,{action,receipt:receipt.trim(),...(decision?{decision,recognitionConsent:recognition}:{})});setResult(response);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const record=result?.record;
  return <section className="panel" id="my-contribution"><p className="eyebrow">YOUR PRIVATE RECEIPT</p><h2>Follow Your Contribution</h2><p>Open your saved receipt to see a response or outcome. You can also open a carrying invitation here.</p><form className="workspace-form" onSubmit={e=>{e.preventDefault();void inspect();}}><label>Receipt code<textarea value={receipt} onChange={e=>{setReceipt(e.target.value);setResult(null);}} rows={3} required autoComplete="off" spellCheck={false}/></label><label>Or load your receipt file<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setError("");try{if(file.size>32000)throw Error("Choose your small receipt JSON file.");const data=JSON.parse(await file.text());if(typeof data.receipt!=="string"||data.receipt.length>2000)throw Error("This file does not contain a receipt.");setReceipt(data.receipt);setResult(null);}catch(err){setError((err as Error).message);}}}/></label><button className="workspace-button secondary" disabled={busy}>{busy?"Checking…":"Open My Receipt"}<RefreshCw size={17}/></button></form>{error&&<p className="workspace-message error" role="alert">{error}</p>}{result && record && <div className="workspace-entry" style={{marginTop:24}}><p className="eyebrow">{result.wave.title}</p><span className="workspace-badge">{record.status}</span><h3>{record.name}</h3>{result.kind==="offer" ? <><p>{(record as WaveOffer).message}</p>{(record as WaveOffer).response&&<div className="workspace-message"><strong>The Team’s Response</strong><p>{(record as WaveOffer).response}</p></div>}{record.outcome&&<><h3>Here’s What Changed</h3><p>{record.outcome}</p><Evidence href={record.evidence}/></>}{record.status!=="withdrawn"&&<button className="workspace-button secondary" disabled={busy} onClick={()=>inspect("withdraw")}>Withdraw My Offer</button>}</> : <><p>{(record as WavePass).purpose}</p><p>Until {formatDate((record as WavePass).expires)}</p>{record.status==="invited"&&<><label className="workspace-check" style={{display:"flex",gap:12,margin:"20px 0"}}><input type="checkbox" checked={recognition} onChange={e=>setRecognition(e.target.checked)}/><span>You may show my name, carrying purpose, and completed outcome publicly.</span></label><div className="workspace-actions"><button className="workspace-button" disabled={busy} onClick={()=>inspect("passReply","accept")}>Accept The Wave<Check size={17}/></button><button className="workspace-button secondary" disabled={busy} onClick={()=>inspect("passReply","decline")}>Decline Invitation</button></div></>}{record.outcome&&<><h3>Here’s What Changed</h3><p>{record.outcome}</p><Evidence href={record.evidence}/></>}</>}{result.journey.length>0&&<details style={{marginTop:20}}><summary>See The Approved Journey</summary>{result.journey.map(item=><article className="workspace-entry" key={item.id}><h3>{item.title}</h3><p>{item.body}</p><Evidence href={item.evidence}/></article>)}</details>}</div>}</section>;
}
