import { useCallback, useEffect, useState } from "react";
import type { FormEvent, ReactNode } from "react";
import { useAuth, UserButton } from "@clerk/react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ArrowRight, Check, Download, LockKeyhole, Plus, RefreshCw } from "lucide-react";
import { ButtonLink, Intro } from "./ui";
import { saveFile, safeWebLink, workspaceRequest, WorkspaceError } from "./workspace-client";
import type { WorkspaceAction, WorkspaceConfig, WorkspaceDetail, WorkspaceList, WorkspaceMutationResult, WorkspaceWave, WaveOffer, WavePass } from "./workspace-types";
import "./workspace.css";

type Run = (action: WorkspaceAction) => Promise<void>;
const value = (form: FormData, name: string) => String(form.get(name) || "").trim();
const date = (time?: string | null) => time ? new Date(time).toLocaleDateString(undefined, { dateStyle: "medium" }) : "Awaiting agreement";
export function Field({ name, label, initial = "", multiline = false, required = false, type = "text", maxLength = 3000 }: { name: string; label: string; initial?: string; multiline?: boolean; required?: boolean; type?: string; maxLength?: number }) {
  return <label>{label}{multiline ? <textarea name={name} defaultValue={initial} required={required} maxLength={maxLength} rows={4} /> : <input name={name} type={type} defaultValue={initial} required={required} maxLength={maxLength} />}</label>;
}
function Submit({ busy, children = "Save Changes" }: { busy: boolean; children?: ReactNode }) { return <button className="workspace-button" disabled={busy} type="submit">{busy ? "Saving…" : children} <Check size={17} /></button>; }
function EmptyWorkspace() { return <div className="workspace-page"><Intro eyebrow="THE WAVE WORKSPACE" title={<>Build Your Wave.<br /><span>Together.</span></>} /><section className="panel"><div className="workspace-auth-icon"><LockKeyhole size={28} /></div><h2>Cohort Invitations Opening Soon</h2><p>A shared place for your mission, your Wave Guide, and your next move. Private workspaces open by invitation once individual accounts are ready.</p><div className="workspace-actions"><ButtonLink to="/guide/library">Explore The Guide Library</ButtonLink><ButtonLink to="/apply" secondary>Bring Your Vision</ButtonLink></div></section></div>; }

export function Workspace() {
  const [config, setConfig] = useState<WorkspaceConfig | null>(null);
  const [error, setError] = useState("");
  const configured = import.meta.env.VITE_WORKSPACE_ENABLED === 'true' && Boolean(import.meta.env.VITE_CLERK_PUBLISHABLE_KEY);
  useEffect(() => { let active = true; workspaceRequest<WorkspaceConfig>("config", null).then(data => { if (active) setConfig(data); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, []);
  if (!configured || config?.ready === false) return <EmptyWorkspace />;
  if (error) return <div className="workspace-page"><section className="panel"><h1>Workspace Temporarily Unavailable</h1><p role="alert">{error}</p><button className="workspace-button" onClick={() => window.location.reload()}>Try Again</button></section></div>;
  if (!config) return <div className="workspace-page workspace-loading" role="status">Opening your workspace…</div>;
  return <AccountWorkspace />;
}

function AccountWorkspace() {
  const { isLoaded, isSignedIn, getToken } = useAuth();
  const { id } = useParams();
  const navigate = useNavigate();
  const [list, setList] = useState<WorkspaceList | null>(null);
  const [detail, setDetail] = useState<WorkspaceDetail | null>(null);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState(""), [passReceipt, setPassReceipt] = useState("");
  const [tab, setTab] = useState("Brief");
  const load = useCallback(async () => {
    if (!isSignedIn) return;
    setLoading(true); setError("");
    try { const token = await getToken(); if (id) setDetail(await workspaceRequest<WorkspaceDetail>("detail", token, undefined, id)); else setList(await workspaceRequest<WorkspaceList>("list", token)); }
    catch (e) { setError((e as Error).message); } finally { setLoading(false); }
  }, [getToken, id, isSignedIn]);
  useEffect(() => { setDetail(null); setTab("Brief"); setNotice(""); setPassReceipt(""); void load(); }, [load]);
  async function run(action: WorkspaceAction) {
    setBusy(true); setError(""); setNotice("");
    try {
      const result = await workspaceRequest<WorkspaceMutationResult>(action.action, await getToken(), action);
      setDetail(result); setNotice(action.action === "publish" ? result.wave.status === "review" ? "Your Wave is ready for its first team review." : "Your approved Wave is now published." : "Saved. Your shared workspace is up to date.");
      if (result.receipt) setPassReceipt(result.receipt);
      if (action.action === "create") navigate(`/workspace/${result.wave.id}`);
    } catch (e) { setError(e instanceof WorkspaceError && e.status === 409 ? "Someone updated this Wave while you were working. Copy any unsaved changes, then refresh before saving again." : (e as Error).message); }
    finally { setBusy(false); }
  }
  if (!isLoaded) return <div className="workspace-page workspace-loading" role="status">Opening your account…</div>;
  if (!isSignedIn) return <div className="workspace-page"><Intro eyebrow="YOUR WAVE WORKSPACE" title="Build Together." /><section className="panel"><div className="workspace-auth-icon"><LockKeyhole size={26} /></div><h2>Your Invitation. Your Account.</h2><p>Sign in with the email invited to your Wave. Builders and Guides work together here, with a private place for the brief, the agreement, and the work in motion.</p><div className="workspace-actions"><ButtonLink to={`/sign-in?redirect_url=${encodeURIComponent(`/workspace${id ? `/${id}` : ""}`)}`}>Sign In</ButtonLink><ButtonLink to="/guide/library" secondary>Explore The Library</ButtonLink></div></section></div>;
  return <div className="workspace-page" data-no-swipe>
    <div className="workspace-toolbar"><Link className="text-button" to="/workspace">Your Workspace</Link><div className="workspace-actions" style={{ margin: 0 }}><button className="workspace-button secondary" disabled={loading || busy} onClick={load}><RefreshCw size={16} />Refresh</button><UserButton /></div></div>
    {error && <p className="workspace-message error" role="alert">{error}</p>}{notice && <p className="workspace-message" role="status">{notice}</p>}
    {loading ? <div className="workspace-loading" role="status">Loading your Waves…</div> : id && detail ? <>
      <Intro eyebrow={`${detail.role.toUpperCase()} WORKSPACE`} title={detail.wave.title}><p>{detail.wave.draft.story ? "Your people. Your purpose. Your next move." : "Begin with the mission. Build your Wave together."}</p></Intro>
      <div className="workspace-toolbar"><span className="workspace-badge">{detail.wave.status} · revision {detail.wave.version}</span><div className="workspace-actions" style={{ margin: 0 }}>{detail.wave.status === "published" && <Link className="workspace-button secondary" to={`/waves/${detail.wave.slug}`}>View Public Wave<ArrowRight size={17} /></Link>}<button className="workspace-button secondary" disabled={busy} onClick={async () => { setBusy(true); setError(""); try { saveFile(`${detail.wave.slug}-workspace.json`, await workspaceRequest("export", await getToken(), undefined, detail.wave.id)); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }}><Download size={17} />Export</button></div></div>
      <nav className="workspace-tabs" aria-label="Workspace sections">{["Brief", "Build", "Current Move", "Contributions", "Journey", ...(detail.isAdmin ? ["People"] : [])].map(name => <button className="workspace-tab" aria-selected={tab === name} aria-current={tab === name ? "page" : undefined} key={name} onClick={() => setTab(name)}>{name}</button>)}</nav>
      <div key={`${detail.wave.id}-${detail.wave.version}-${tab}`} className="workspace-stack">
        {tab === "Brief" && <BriefPanel detail={detail} run={run} busy={busy} />}
        {tab === "Build" && <BuildPanel detail={detail} run={run} busy={busy} />}
        {tab === "Current Move" && <MovePanel detail={detail} run={run} busy={busy} />}
        {tab === "Contributions" && <ContributionPanel detail={detail} run={run} busy={busy} receipt={passReceipt} />}
        {tab === "Journey" && <JourneyPanel detail={detail} run={run} busy={busy} />}
        {tab === "People" && detail.isAdmin && <PeoplePanel wave={detail.wave} run={run} busy={busy} />}
      </div>
    </> : !id && list ? <>
      <Intro eyebrow="YOUR WAVES" title={<>The Work.<br /><span>In Motion.</span></>}><p>A shared place to build, contribute, and see what changed.</p></Intro>
      {list.waves.length ? <div className="workspace-grid">{list.waves.map(wave => <Link className="panel workspace-card-link" to={`/workspace/${wave.id}`} key={wave.id}><span className="workspace-badge">{wave.status}</span><h2>{wave.title}</h2><p>{wave.currentMove.title || "Define your first move together."}</p><div className="workspace-actions"><span>{wave.role || "Team"}</span><ArrowRight size={19} /></div></Link>)}</div> : <section className="panel"><h2>Your First Wave Starts With A Conversation.</h2><p>No Waves are assigned to this account yet. Your team will add your invited email when your engagement is ready.</p><ButtonLink to="/guide/library" secondary>Explore The Guide Library</ButtonLink></section>}
      {list.isAdmin && <CreateWave busy={busy} run={run} />}
    </> : null}
  </div>;
}

type PanelProps = { detail: WorkspaceDetail; run: Run; busy: boolean };
function roles(detail: WorkspaceDetail) { return detail.roles || [detail.role]; }
function BriefPanel({ detail, run, busy }: PanelProps) {
  const w = detail.wave; const editable = roles(detail).some(r => ["builder", "guide", "support"].includes(r)); const lead = roles(detail).some(r => r === "builder" || r === "guide");
  return <><section className="panel"><p className="eyebrow">START WITH THE HUMAN</p><h2>The Shared Brief</h2>{!editable && <p>Team review access. The assigned builder and Guides edit this brief.</p>}<fieldset className="workspace-permission" disabled={!editable}><form className="workspace-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void run({ action: "update", id: w.id, version: w.version, brief: { mission: value(f,"mission"), audience: value(f,"audience"), needs: value(f,"needs") } }); }}><Field name="mission" label="What are we here to do?" initial={w.brief.mission} multiline required /><Field name="audience" label="Who are we building for?" initial={w.brief.audience} multiline /><Field name="needs" label="What help, resources, or context do we need?" initial={w.brief.needs} multiline /><Submit busy={busy}>Save The Brief</Submit></form></fieldset></section>
    <section className="panel"><p className="eyebrow">AGREE BEFORE BUILDING</p><h2>The Engagement</h2><p>Agree the work, the fee, and the handover together. Invoices and payments are arranged directly with your Guide.</p>{lead ? <form className="workspace-form two-column" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void run({action:"update",id:w.id,version:w.version,engagement:{scope:value(f,"scope"),fee:value(f,"fee"),paymentSchedule:value(f,"paymentSchedule"),deliveryWindow:value(f,"deliveryWindow"),revisions:value(f,"revisions"),ownership:value(f,"ownership"),support:value(f,"support")}}); }}><Field name="scope" label="Scope & deliverables" initial={w.engagement.scope} multiline required /><Field name="fee" label="Agreed fee & currency" initial={w.engagement.fee} required /><Field name="paymentSchedule" label="Payment schedule · fixed, weekly, or monthly" initial={w.engagement.paymentSchedule} required /><Field name="deliveryWindow" label="Delivery window" initial={w.engagement.deliveryWindow} required /><Field name="revisions" label="Included revisions" initial={w.engagement.revisions} multiline /><Field name="ownership" label="Ownership & handover" initial={w.engagement.ownership} multiline required /><Field name="support" label="Ongoing support & maintenance" initial={w.engagement.support} multiline /><div className="workspace-actions"><Submit busy={busy}>Save Engagement</Submit></div></form> : <dl className="workspace-detail">{Object.entries(w.engagement).filter(([key]) => !key.endsWith("At")).map(([key,text]) => <div key={key}><dt>{key.replace(/([A-Z])/g," $1")}</dt><dd>{text || "To be agreed"}</dd></div>)}</dl>}
    <p className="workspace-note">Builder agreement: {date(w.engagement.builderApprovedAt)}<br />Guide agreement: {date(w.engagement.guideApprovedAt)}. Changing the terms asks both people to agree again.</p><div className="workspace-actions">{roles(detail).includes("builder") && <button className="workspace-button" disabled={busy || !!w.engagement.builderApprovedAt} onClick={() => run({action:"approveEngagement",id:w.id,version:w.version,as:"builder"})}>Agree As Builder</button>}{roles(detail).includes("guide") && <button className="workspace-button" disabled={busy || !!w.engagement.guideApprovedAt} onClick={() => run({action:"approveEngagement",id:w.id,version:w.version,as:"guide"})}>Agree As Guide</button>}</div></section></>;
}

function BuildPanel({ detail, run, busy }: PanelProps) {
  const w=detail.wave; const editable = roles(detail).some(r => ["builder", "guide", "support"].includes(r));
  return <><section className="panel"><p className="eyebrow">YOUR WAVE, CUSTOM BUILT</p><h2>The Story & The Build</h2><p>Shape the public story here. Your Guide builds the tools and experience your mission needs, and records the handover alongside it.</p>{!editable && <p>Team review access. The assigned builder and Guides edit this story.</p>}<fieldset className="workspace-permission" disabled={!editable}><form className="workspace-form" onSubmit={e => {e.preventDefault();const f=new FormData(e.currentTarget);void run({action:"update",id:w.id,version:w.version,draft:{title:value(f,"title"),story:value(f,"story"),guideName:value(f,"guideName"),guideBio:value(f,"guideBio"),buildNotes:value(f,"buildNotes"),deliverableUrl:value(f,"deliverableUrl")}});}}><Field name="title" label="Wave title" initial={w.draft.title} required maxLength={120} /><Field name="story" label="The story · for the public Wave" initial={w.draft.story} multiline required maxLength={12000} /><div className="workspace-grid"><Field name="guideName" label="Lead Wave Guide · public name" initial={w.draft.guideName} required maxLength={120} /><Field name="guideBio" label="About your Guide · public" initial={w.draft.guideBio} multiline /></div><Field name="deliverableUrl" label="Private build or handover link" type="url" initial={w.draft.deliverableUrl} /><Field name="buildNotes" label="Private build notes · tools, decisions, and maintenance" initial={w.draft.buildNotes} multiline maxLength={12000} /><Submit busy={busy}>Save The Build</Submit></form></fieldset></section>
    <section className="panel"><h2>Approve What The World Sees</h2><p>Your public Wave includes the story and Guide bio above, your current move, Journey entries, and completed contributions with consent. Private briefs, engagement terms, build notes, and contact details stay in this workspace.</p>{w.published && <p className="workspace-note">Last published {date(w.published.publishedAt)}. New edits stay private until the builder publishes them.</p>}{w.status==="review" && <p className="workspace-message">Your first publication is awaiting team review.</p>}<div className="workspace-actions">{roles(detail).includes("builder") && <button className="workspace-button" disabled={busy || w.status==="review"} onClick={() => run({action:"publish",id:w.id,version:w.version})}>{w.initialReviewAt ? "Approve & Publish Changes" : "Approve & Send For Review"}<ArrowRight size={17} /></button>}{detail.isAdmin && w.status==="review" && <><button className="workspace-button" disabled={busy} onClick={() => run({action:"review",id:w.id,version:w.version,decision:"approve"})}>Approve First Publication</button><button className="workspace-button secondary" disabled={busy} onClick={() => run({action:"review",id:w.id,version:w.version,decision:"return"})}>Return For Changes</button></>}{(detail.isAdmin || roles(detail).includes("builder")) && w.status==="published" && <button className="workspace-button secondary" disabled={busy} onClick={() => run({action:"pause",id:w.id,version:w.version})}>Pause Public Wave</button>}</div></section></>;
}

function MovePanel({detail,run,busy}:PanelProps) {
  const w=detail.wave;const canEdit=roles(detail).some(r=>r==="builder"||r==="guide");
  return <section className="panel"><p className="eyebrow">ONE CLEAR NEXT MOVE</p><h2>{w.currentMove.title || "What Happens Next?"}</h2><p>Name the outcome, the person responsible, and the help that moves it forward. Completing a move records its outcome in the Journey. Then open the next move.</p><form className="workspace-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run({action:"update",id:w.id,version:w.version,currentMove:{id:w.currentMove.id||crypto.randomUUID(),title:value(f,"title"),owner:value(f,"owner"),needs:value(f,"needs"),completion:value(f,"completion"),status:value(f,"status") as "open"|"complete",evidence:value(f,"evidence"),outcome:value(f,"outcome")}});}}><fieldset disabled={!canEdit || busy} style={{border:0,padding:0,margin:0,display:"grid",gap:18}}><Field name="title" label="The next move" initial={w.currentMove.title} required maxLength={160} /><Field name="owner" label="Who is responsible?" initial={w.currentMove.owner} required /><Field name="needs" label="Help needed" initial={w.currentMove.needs} multiline required /><Field name="completion" label="How will we know it is complete?" initial={w.currentMove.completion} multiline required /><label>Status<select name="status" defaultValue={w.currentMove.status}><option value="open">Open · help welcome</option><option value="complete">Complete · outcome recorded</option></select></label><Field name="outcome" label="What changed?" initial={w.currentMove.outcome} multiline /><Field name="evidence" label="Public evidence link" initial={w.currentMove.evidence} type="url" /></fieldset>{canEdit && <div className="workspace-actions"><Submit busy={busy}>Save This Move</Submit>{w.currentMove.status==="complete" && <button type="button" className="workspace-button secondary" disabled={busy} onClick={()=>run({action:"update",id:w.id,version:w.version,currentMove:{id:crypto.randomUUID(),title:"",owner:"",needs:"",completion:"",status:"open",evidence:"",outcome:""}})}>Open The Next Move</button>}</div>}</form></section>;
}

function ContributionPanel({detail,run,busy,receipt}:PanelProps & {receipt:string}) {
  const w=detail.wave;const canEdit=roles(detail).some(r=>r==="builder"||r==="guide");
  return <><section className="panel"><p className="eyebrow">HELP BECOMES ACTION</p><h2>Contributions</h2>{w.offers.length ? w.offers.map(offer=><OfferEditor key={offer.id} wave={w} offer={offer} run={run} busy={busy} canEdit={canEdit} />) : <p>Offers of help will arrive here from your published Wave. Acknowledge each person, agree the work, and show what changed.</p>}</section><section className="panel"><p className="eyebrow">PASS THE WAVE</p><h2>Invite Someone To Carry It</h2><p>Agree a purpose and a period. Create a private invitation and share it yourself with the person you have in mind. Ownership stays with the builder.</p>{canEdit && <form className="workspace-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run({action:"pass",id:w.id,version:w.version,name:value(f,"name"),purpose:value(f,"purpose"),expires:new Date(value(f,"expires")).toISOString()});}}><Field name="name" label="Who is invited?" required maxLength={120}/><Field name="purpose" label="What would you like them to do?" multiline required/><Field name="expires" label="Invitation and carrying period ends · within 90 days" type="datetime-local" required/><Submit busy={busy}>Create A Private Invitation</Submit></form>}{receipt && <div className="workspace-message"><strong>Keep And Share This Invitation</strong><p>Send this receipt directly to the invited person, together with your public Wave link. It gives access to their invitation.</p><p className="workspace-receipt">{receipt}</p><button className="workspace-button secondary" onClick={()=>saveFile(`${w.slug}-invitation.json`,{receipt,slug:w.slug,url:`https://www.waves.fund/waves/${w.slug}`,kind:"pass"})}><Download size={17}/>Download Invitation</button></div>}{w.passes.map(pass=><PassEditor key={pass.id} wave={w} pass={pass} run={run} busy={busy} canEdit={canEdit}/>)}</section></>;
}
function OfferEditor({wave:w,offer,run,busy,canEdit}:{wave:WorkspaceWave;offer:WaveOffer;run:Run;busy:boolean;canEdit:boolean}) {
  return <article className="workspace-entry"><span className="workspace-badge">{offer.status}</span><h3>{offer.name}</h3><p>{offer.message}</p><p className="workspace-note">{offer.email}<br/>Public recognition {offer.recognitionConsent?"permitted":"not permitted"} · {date(offer.created)}</p>{canEdit && <details><summary>Respond & Record Progress</summary><form className="workspace-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run({action:"offer",id:w.id,version:w.version,offerId:offer.id,status:value(f,"status") as WaveOffer["status"],response:value(f,"response"),outcome:value(f,"outcome"),evidence:value(f,"evidence")});}}><label>Contribution status<select name="status" defaultValue={offer.status} disabled={offer.status==="withdrawn"}>{[offer.status,...({offered:["acknowledged","declined"],acknowledged:["agreed","declined"],agreed:["completed","declined"],completed:[],declined:[],withdrawn:[]}[offer.status])].map(s=><option key={s} value={s}>{s}</option>)}</select></label><Field name="response" label="Private response · visible through their receipt" initial={offer.response} multiline/><Field name="outcome" label="Outcome · eligible for publication with consent" initial={offer.outcome} multiline/><Field name="evidence" label="Public evidence link" initial={offer.evidence} type="url"/><Submit busy={busy || offer.status==="withdrawn"}>Save Contribution</Submit></form></details>}</article>;
}
function PassEditor({wave:w,pass,run,busy,canEdit}:{wave:WorkspaceWave;pass:WavePass;run:Run;busy:boolean;canEdit:boolean}) {
  return <article className="workspace-entry"><span className="workspace-badge">{pass.status}</span><h3>{pass.name}</h3><p>{pass.purpose}</p><p className="workspace-note">Until {date(pass.expires)} · public recognition {pass.recognitionConsent?"permitted":"not permitted"}</p>{canEdit && (pass.status==="accepted" || pass.status==="invited") && <details><summary>Record The Handoff Outcome</summary><form className="workspace-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run({action:"passUpdate",id:w.id,version:w.version,passId:pass.id,status:value(f,"status") as "completed"|"revoked",outcome:value(f,"outcome"),evidence:value(f,"evidence")});}}><label>Status<select name="status" defaultValue={pass.status==="accepted"?"completed":"revoked"}>{pass.status==="accepted" && <option value="completed">Completed</option>}<option value="revoked">Revoke invitation</option></select></label><Field name="outcome" label="What happened?" initial={pass.outcome} multiline/><Field name="evidence" label="Public evidence link" initial={pass.evidence} type="url"/><Submit busy={busy}>Save Outcome</Submit></form></details>}</article>;
}

function JourneyPanel({detail,run,busy}:PanelProps) {
  const w=detail.wave; const editable = roles(detail).some(r => ["builder", "guide", "support"].includes(r));
  return <section className="panel"><p className="eyebrow">YOU HELPED. HERE’S WHAT CHANGED.</p><h2>The Journey</h2><p>Add an outcome, a decision, or a milestone. These entries become public only when the builder approves publication. Share other people’s names and work only with their permission.</p>{w.journey.map(item=><article className="workspace-entry" key={item.id}><time dateTime={item.created}>{date(item.created)}</time><h3>{item.title}</h3><p>{item.body}</p>{safeWebLink(item.evidence)&&<a className="text-button" href={safeWebLink(item.evidence)} target="_blank" rel="noreferrer">View Evidence<ArrowRight size={16}/></a>}</article>)}<fieldset className="workspace-permission" disabled={!editable}><form className="workspace-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run({action:"update",id:w.id,version:w.version,journey:[...w.journey,{id:crypto.randomUUID(),title:value(f,"title"),body:value(f,"body"),evidence:value(f,"evidence"),created:new Date().toISOString()}]});}}><Field name="title" label="Milestone or outcome" required maxLength={160}/><Field name="body" label="What changed, and what did we learn?" multiline required/><Field name="evidence" label="Public evidence link" type="url"/><Submit busy={busy}>Add To The Journey</Submit></form></fieldset></section>;
}

function PeoplePanel({wave:w,run,busy}:{wave:WorkspaceWave;run:Run;busy:boolean}) {return <section className="panel"><h2>The People Building This Wave</h2><p>Assign access to a verified account email. Invitations to create an account are managed separately through the account provider.</p>{w.members.map(member=><div key={`${member.email}-${member.role}`} className="workspace-person"><div><p>{member.email}</p><small>{member.role}</small></div><button className="workspace-button secondary" disabled={busy} onClick={()=>run({action:"member",id:w.id,version:w.version,email:member.email,role:member.role,remove:true})}>Remove</button></div>)}<form className="workspace-form" style={{marginTop:24}} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run({action:"member",id:w.id,version:w.version,email:value(f,"email"),role:value(f,"role") as "builder"|"guide"|"support"});}}><Field name="email" label="Verified account email" required type="email"/><label>Role<select name="role" defaultValue="support"><option value="builder">Builder · ownership & publication</option><option value="guide">Lead Guide · delivery & coordination</option><option value="support">Supporting Guide · brief, build, and Journey</option></select></label><Submit busy={busy}>Assign Access</Submit></form></section>;}

function CreateWave({run,busy}:{run:Run;busy:boolean}) {const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void run({action:"create",title:value(f,"title"),slug:value(f,"slug"),template:value(f,"template"),builderEmail:value(f,"builderEmail"),guideEmail:value(f,"guideEmail"),legacyApplicationId:value(f,"legacyApplicationId")});};return <section className="panel" style={{marginTop:28}}><details><summary><Plus size={17} style={{verticalAlign:"middle",marginRight:8}}/>Set Up A Wave</summary><p>Create the workspace after agreeing who is building and who is guiding. This does not publish a project or send an invitation.</p><form className="workspace-form two-column" onSubmit={submit}><Field name="title" label="Wave title" required maxLength={120}/><Field name="slug" label="Permanent address · lowercase words and hyphens" required maxLength={80}/><Field name="builderEmail" label="Builder email" required type="email"/><Field name="guideEmail" label="Lead Guide email" required type="email"/><label>Starting model<select name="template" defaultValue=""><option value="">Custom Wave</option>{["Growth","Funding","Innovation","Story","Hype","Maker","Work","Brave"].map(t=><option value={t.toLowerCase()} key={t}>{t} Wave</option>)}</select></label><Field name="legacyApplicationId" label="Existing application ID · optional"/><div className="workspace-actions"><Submit busy={busy}>Create Workspace</Submit></div></form></details></section>;}
